// ---------------------------------------------------------------------------
// @media-scraper/core — types
// ---------------------------------------------------------------------------

/** Category of extracted media. */
export type MediaType = 'image' | 'video' | 'audio' | 'document' | 'unknown';

/**
 * Origin within the page from which a media resource was discovered.
 *
 * - `img`         – standard `<img>` elements
 * - `video`       – `<video>` elements and their `<source>` children
 * - `audio`       – `<audio>` elements and their `<source>` children
 * - `background`  – CSS `background-image` / `background` on any element
 * - `link`        – `<a href>` links that point to media files
 * - `lazy-load`   – attributes like `data-src`, `data-original`, etc.
 * - `iframe`      – media embedded inside `<iframe>` elements
 * - `shadow-dom`  – media discovered inside Shadow DOM trees
 * - `head-meta`   – `<meta>` tags (e.g. `og:image`, `twitter:image`)
 * - `m3u8`        – HLS `.m3u8` playlist URLs
 * - `mpd`         – MPEG-DASH `.mpd` manifest URLs
 */
export type MediaSource =
  | 'img'
  | 'video'
  | 'audio'
  | 'background'
  | 'link'
  | 'lazy-load'
  | 'iframe'
  | 'shadow-dom'
  | 'head-meta'
  | 'm3u8'
  | 'mpd';

/** A single media resource discovered on a page. */
export interface MediaResource {
  /** Unique identifier for this resource (generated by the scraper). */
  id: string;
  /** Absolute or fully-qualified URL of the media file. */
  url: string;
  /** Broad category of the media. */
  type: MediaType;
  /** Inferred filename (derived from the URL path). */
  filename: string;
  /** Lowercase file extension including the dot (e.g. ".jpg"). */
  extension: string;
  /** File size in bytes (0 when unknown). */
  size: number;
  /** Natural / intrinsic width in pixels (0 when unknown). */
  width: number;
  /** Natural / intrinsic height in pixels (0 when unknown). */
  height: number;
  /** URL of a thumbnail / poster image when available. */
  thumbnail: string;
  /** How this resource was discovered on the page. */
  source: MediaSource;
}

/** The result of scraping a single URL. */
export interface ScrapeResult {
  /** The URL that was scraped. */
  url: string;
  /** Page title (extracted from `<title>`). */
  title: string;
  /** Total number of media resources discovered. */
  total: number;
  /** Discovered images. */
  images: MediaResource[];
  /** Discovered videos. */
  videos: MediaResource[];
  /** Discovered audio files. */
  audio: MediaResource[];
  /** Discovered documents. */
  documents: MediaResource[];
  /** How long the scrape took (milliseconds). */
  duration: number;
  /** ISO-8601 timestamp of when the scrape completed. */
  timestamp: string;
}

/** Options that control scraping behaviour. */
export interface ScrapeOptions {
  /** The URL of the page to scrape. */
  url: string;
  /** Media types to include. Omit to include all. */
  types?: MediaType[];
  /** Minimum file size in bytes to include. */
  minSize?: number;
  /** Maximum number of pages to crawl (for multi-page galleries). */
  maxPages?: number;
  /** How deep to follow links when crawling. */
  exploreDepth?: number;
  /** Timeout for the page load in milliseconds. */
  timeout?: number;
  /** Proxy URL (e.g. "http://user:pass@host:port"). */
  proxy?: string;
  /** Custom User-Agent header. */
  userAgent?: string;
}

/** Options controlling how resources are downloaded to disk. */
export interface DownloadOptions {
  /** The resources to download. */
  resources: MediaResource[];
  /** Destination directory for downloaded files. */
  outputDir: string;
  /** Maximum number of concurrent downloads. */
  concurrency?: number;
  /** When `true`, group files into subdirectories by media type. */
  organizeByType?: boolean;
  /** Optional progress callback invoked after each file completes. */
  onProgress?: (progress: DownloadProgress) => void;
}

/** Snapshot of download progress. */
export interface DownloadProgress {
  /** Number of files fully downloaded so far. */
  completed: number;
  /** Total number of files to download. */
  total: number;
  /** The resource currently being downloaded (if any). */
  current: MediaResource | null;
  /** Estimated download speed in bytes per second. */
  speed: number;
}

/** Options for filtering a list of media resources. */
export interface FilterOptions {
  /** Only keep resources matching these media types. */
  types?: MediaType[];
  /** Minimum width in pixels. */
  minWidth?: number;
  /** Minimum height in pixels. */
  minHeight?: number;
  /** Minimum file size in bytes. */
  minSize?: number;
  /** Only keep resources whose URL hostname matches this domain. */
  domain?: string;
  /** File extensions to exclude (e.g. [".gif", ".svg"]). */
  excludeExtensions?: string[];
}

// ---------------------------------------------------------------------------
// DOM abstraction – keeps core browser-compatible (no Node APIs)
// ---------------------------------------------------------------------------

/**
 * Minimal DOM-like interface consumed by extractors.
 *
 * Concrete implementations can be backed by a real browser DOM (jsdom /
 * happy-dom) or a lightweight parse tree — the core package never imports
 * `fs`, `path`, `process`, or any Node-specific modules.
 */
export interface DocumentLike {
  querySelectorAll(selector: string): ElementLike[];
  querySelector(selector: string): ElementLike | null;
  title: string;
  head?: ElementLike | null;
  body?: ElementLike | null;
}

export interface ElementLike {
  tagName: string;
  getAttribute(name: string): string | null;
  querySelectorAll(selector: string): ElementLike[];
  querySelector(selector: string): ElementLike | null;
  textContent: string | null;
}
